[package]
name = "snake-sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2-sys = "0.35.2"
rand = "0.8.5"

# logging
log = "0.4.17"
pretty_env_logger = "0.4.0"
